_BASE_: "Base-DeformDETR_L_R50_4x.yaml"
FIND_UNUSED_PARAM: False 
MODEL:
  WEIGHTS: "weights/resnet50_miil_21k.pkl" 
  BACKBONE:
    NAME: build_timm_backbone 
  TIMM:
    BASE_NAME: resnet50_in21k 
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  DETR:
    NUM_CLASSES: 1203 
    USE_BIAS: -4.59511985013459
    USE_ZEROSHOT_CLS: True 
    NORM_WEIGHT: True 
    IN_FEATURES: ('layer3','layer4','layer5') 
    LOOK_FORWARD_TWICE: True 
    DROPOUT: 0.0 
SOLVER:
  STEPS: (300000,)
  MAX_ITER: 360000
  IMS_PER_BATCH: 16
DATASETS:
  TRAIN: ("lvis_v1_train",)
DATALOADER:
  NUM_WORKERS: 8
FP16: True 