_BASE_: "BoxSup-DeformDETR_Lbase_CLIP_R5021k_4x.yaml"
MODEL:
  WEIGHTS: "BoxSup-DeformDETR_Lbase_CLIP_R5021k_4x.pth"
  DETR:
    NUM_CLASSES: 20345 
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/lvis-21k_clip_a+cname.npy'
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: [480, 800]
DATASETS:
  TRAIN: ("lvis_v1_train_norare","imagenet_lvis-21k")
  TEST: ("lvis_v1_val",)
SOLVER:
  STEPS: (300000,)
  MAX_ITER: 360000
  IMS_PER_BATCH: 16
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 16]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [2, 8]
  USE_RFS: [True, False]
  DATASET_MIN_SIZES: [[480, 800], [240, 400]]
  DATASET_MAX_SIZES: [1333, 667]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  USE_TAR_DATASET: True
SOLVER:
  STEPS: (300000,)
  MAX_ITER: 360000
WITH_IMAGE_LABELS: True
