_BASE_: "Base-DeformDETR_L_R50_4x.yaml"
FIND_UNUSED_PARAM: False 
MODEL:
  META_ARCHITECTURE: "DECOLA_DeformableDETR"
  WEIGHTS: "weights/swin_tiny_patch4_window7_224.pkl"
  BACKBONE:
    NAME: build_swintransformer_backbone
  SWIN:
    SIZE: T
    OUT_FEATURES: [1, 2, 3]
    USE_CHECKPOINT: False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  DECOLA:
    ORACLE_EVALUATION: True 
    USE_PROMPT_EMBED_BIAS: True 
    PER_PROMPT_TOPK: 300
    USE_PIXEL_FEATURE_AS_QUERY: True 
    SECOND_STAGE_EMBED_NORM: True 
    FIRST_STAGE_EMBED_NORM: True
    USE_PROMPT_EMBED_AS_QUERY: False  # for ablation
    PROB_A_OBJECT: 0.0                # probability of using "a object." as prompt.
    TEST_CLASS_CONDITIONED: True      # class-conditioned detection
    FIRST_STAGE_ENC_LOSS_PER_PROMPT_TOPK: 10000
    ZS_WEIGHT_PATH: "datasets/metadata/o365_clip_a+cnamefix.npy" 
  DETR:
    NUM_FEATURE_LEVELS: 4
    DROPOUT: 0.0 
    LOOK_FORWARD_TWICE: True 
    DIM_FEEDFORWARD: 2048 
    NUM_CLASSES: 365 
    USE_BIAS: -4.59511985013459 
    USE_ZEROSHOT_CLS: True 
    NORM_WEIGHT: True 
    USE_FED_LOSS: False 
    IN_FEATURES: ["swin1", "swin2", "swin3"] 
DATASETS:
  TRAIN: ("objects365_v1_train",)
  TEST: ("objects365_v1_val",)
SOLVER:
  STEPS: (899706,) # ~88%
  MAX_ITER: 1022394 # = 545277 (images) * 30 (epochs) / 16 (batch-size)
  IMS_PER_BATCH: 16
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
  SAMPLER_TRAIN: "TrainingSampler" # no rfs
  REPEAT_THRESHOLD: 0.0
FP16: True 