_BASE_: "Base-DeformDETR_L_R50_4x.yaml"
FIND_UNUSED_PARAM: False 
MODEL:
  META_ARCHITECTURE: "DECOLA_DETA"
  WEIGHTS: "weights/deta/adet_swin_pt_o365.pkl"
  BACKBONE:
    NAME: build_swintransformer_backbone
  SWIN:
    SIZE: L-22k-384
    OUT_FEATURES: [1, 2, 3]
    USE_CHECKPOINT: False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  DECOLA:
    ORACLE_EVALUATION: True 
    USE_PROMPT_EMBED_BIAS: True 
    PER_PROMPT_TOPK: 300
    USE_PIXEL_FEATURE_AS_QUERY: True 
    SECOND_STAGE_EMBED_NORM: True 
    FIRST_STAGE_EMBED_NORM: True
    USE_PROMPT_EMBED_AS_QUERY: False  
    PROB_A_OBJECT: 0.0
    DETA:
      USE_DETA: True 
  DETR:
    NUM_FEATURE_LEVELS: 5
    DROPOUT: 0.0 
    LOOK_FORWARD_TWICE: True 
    DIM_FEEDFORWARD: 2048 
    NUM_CLASSES: 1203 
    USE_BIAS: -4.59511985013459
    USE_ZEROSHOT_CLS: True 
    NORM_WEIGHT: True 
    IN_FEATURES: ["swin1", "swin2", "swin3"] 
DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
  TEST: ("lvis_v1_val",)
SOLVER:
  STEPS: (300000,)
  MAX_ITER: 360000
  IMS_PER_BATCH: 16
DATALOADER:
  NUM_WORKERS: 8
FP16: True 