_BASE_: "Base-DeformDETR_L_R50_4x.yaml"
FIND_UNUSED_PARAM: False 
MODEL:
  META_ARCHITECTURE: "DECOLA_DeformableDETR"
  WEIGHTS: "weights/resnet50_miil_21k.pkl" 
  BACKBONE:
    NAME: build_timm_backbone 
  TIMM:
    BASE_NAME: resnet50_in21k 
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  DECOLA:
    ORACLE_EVALUATION: True 
    USE_PROMPT_EMBED_BIAS: True 
    PER_PROMPT_TOPK: 300
    USE_PIXEL_FEATURE_AS_QUERY: True 
    SECOND_STAGE_EMBED_NORM: True 
    FIRST_STAGE_EMBED_NORM: True
    USE_PROMPT_EMBED_AS_QUERY: False  # for ablation
    PROB_A_OBJECT: 0.0                # probability of using "a object." as prompt.
    TEST_CLASS_CONDITIONED: True      # class-conditioned detection
    FIRST_STAGE_ENC_LOSS_PER_PROMPT_TOPK: 10000
  DETR:
    DROPOUT: 0.0 
    LOOK_FORWARD_TWICE: True 
    NUM_CLASSES: 1203 
    USE_BIAS: -4.59511985013459
    USE_ZEROSHOT_CLS: True 
    NORM_WEIGHT: True 
    IN_FEATURES: ('layer3','layer4','layer5')
DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
  TEST: ("lvis_v1_val",)
SOLVER:
  STEPS: (300000,)
  MAX_ITER: 360000
  IMS_PER_BATCH: 16
DATALOADER:
  NUM_WORKERS: 8
FP16: True 