_BASE_: "DECOLA_PHASE1_L_CLIP_SwinB_4x.yaml"
MODEL:
  WEIGHTS: "weights/DECOLA_PHASE1_L_CLIP_SwinB_4x.pth"
  DECOLA:
    ORACLE_EVALUATION: True 
    TEST_CLASS_CONDITIONED: True
    WEAK_LOSS_PSEUDO_TYPE: max-score
GEN_PSEDO_LABELS: True 
WITH_IMAGE_LABELS: True 
TEST:
  BATCH_SIZE: 1
  JUST_STORE_PREDICTIONS: True 
  PREDICTION_SAVE_FILENAME: "phase1_swinb_ddetr_4x"
DATASETS:
  TRAIN: ("imagenet_lvis_v1",)
  TEST: ("imagenet_lvis_v1",)
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: [480, 800]
  MIN_SIZE_TEST: 400 # change this for different image resolution.
  MAX_SIZE_TEST: 667
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  FILTER_EMPTY_ANNOTATIONS: False 
  MULTI_DATASET_GROUPING: True
  NUM_WORKERS: 8
  DATASET_ANN: ['image'] 
  DATASET_BS: [1] 
  DATASET_RATIO: [1] 
  USE_RFS: [False]
  DATASET_INPUT_SIZE: [384]
  DATASET_MIN_SIZES: [[240, 400]]
  DATASET_MAX_SIZES: [667]
  DATASET_INPUT_SCALE: [[0.5, 1.5]]
  DATASET_INPUT_SCALE: [[320, 400]]
